import Head from 'next/head'
import React, { useState } from 'react'
import SearchBox from './components/autoinput'
import Card from './components/card1'
import Card2 from './components/card2'
import FeedbackForm from './components/feedbackform'


function MyComponent() {
  const [responses, setResponses] = useState('');
  const [loaded, setLoaded] = useState(false);
  const [city, setCity] = useState('');

  const handleSubmit = async (input, params) => {
    setCity(input)
    const response = await fetch('https://test-flask-vercel-ten.vercel.app/api/sus', {
    // const response = await fetch('http://localhost:5000/api/sus', {
    
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ input, params })
    });
    
    const data = await response.json()
    setLoaded(true)
    setResponses(data)
  }
  return (
    <>
      <div className="container mx-auto w-2/3 pt-24">
      <h1 className="my-10 mx-auto max-w-4xl font-display text-5xl text-align-center font-medium text-slate-900 sm:text-6xl">Vacation Made Simple for You</h1>
        <SearchBox onSubmit={handleSubmit}/>

      </div>
      {/* <div>{JSON.stringify(responses)}</div> */}
      {loaded && (
        <div>
          <div className="flex pt-10">
            <div className="w-1/2">
              
              <h1 className="text-center">Vacation spots in {city}</h1>
              {responses.map((response) => (
                <Card key={response.id} data={response}/>
              ))}
            </div>
            
            <Card2 data={city} onSubmit={handleSubmit}/>
          </div>
          <div className="w-1/2 my-10 py-6 mx-auto bg-blue-200 rounded-2xl">
            <FeedbackForm />
          </div>
        </div>
      )}
      {/* {!loaded && <h1 >Loading...</h1>} */}
    </>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Vacation Recommender</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <MyComponent class="bg-blue" />
      </main>
    </>
  )
}



