import Head from 'next/head'
import React, { useState } from 'react'
import SearchBox from './components/autoinput'
import Image from 'next/image'
import Card from './components/card1'
import Card2 from './components/card2'
import Card3 from './components/card3'
import FeedbackForm from './components/feedbackform'

function MyComponent() {
  const [responses, setResponses] = useState('');
  const [loaded, setLoaded] = useState(false);
  const [loading, setLoading] = useState(false);
  const [city, setCity] = useState('');
  const [weather1, setWeather1] = useState('');
  const [weather2, setWeather2] = useState('');

  const handleSubmit = async (input, params) => {
    setCity(input)
    setLoaded(false);
    setLoading(true);
    const response = await fetch('https://test-flask-vercel-ten.vercel.app/api/sus', {
    // const response = await fetch('http://localhost:5000/api/sus', {
    
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ input, params })
    });
    
    const data = await response.json()
    setLoaded(true)
    setWeather1("https:"+data.weather.icon)
    setWeather2("https:"+data.tomorrow.icon)
    setResponses(data.result)
    setLoading(false);
  }
  return (
    <>
      <div className="container mx-auto w-2/3 pt-24">
      <h1 className="my-10 mx-auto max-w-4xl font-display text-5xl text-align-center font-medium text-slate-900 sm:text-6xl">Vacation Made Simple for You</h1>
        <SearchBox onSubmit={handleSubmit}/>
      </div>
      {loaded && (
        <div>
          <div className="mx-auto mt-5 w-1/2 flex-col">
            <h1 className="text-center font-semibold text-3xl">{city}</h1>
            <div className="flex justify-evenly">
              <div>
                <h1>Currently</h1>
                <Image className="mx-auto" src={weather1} alt="Weather" width="64" height="64"/>
              </div>
              <div>
                <h1>Tomorrow</h1>
                <Image className="mx-auto" src={weather2} alt="Weather" width="64" height="64"/>
              </div>
            </div>
          </div>
          <div className="flex pt-10">
            <div className="w-1/3">
              
              <h1 className="text-center">Vacation spots in {city}</h1>
              {responses.map((response) => (
                <Card key={response.id} data={response}/>
              ))}
            </div>
            
            <Card2 data={city} onSubmit={handleSubmit}/>
            <Card3 data={city} onSubmit={handleSubmit}/>
          </div>
          <div className="w-1/2 my-10 py-6 mx-auto bg-blue-200 rounded-2xl">
            <FeedbackForm />
          </div>
        </div>
      )}
      {loading && 
      <div className="flex justify-center items-center h-1/2">
        <p>Loading...</p>
      </div>}
    </>
  );
}

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Vacation Recommender</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <MyComponent class="bg-blue" />
      </main>
    </>
  )
}



