import Head from 'next/head'
import { Inter } from 'next/font/google'
import React, { useState } from 'react'
import SearchBox from './components/autoinput'
import Card from './components/card1'
import Card2 from './components/card2'

const inter = Inter({ subsets: ['latin'] })

function MyComponent() {
  const [responses, setResponses] = useState('');
  const [loaded, setLoaded] = useState(false);
  const [city, setCity] = useState('');

  const handleSubmit = async (input) => {
    setCity(input)
    const response = await fetch('http://localhost:5000/api/sus', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ input })
    });
    
    const data = await response.json()
    setLoaded(true)
    setResponses(data)
  }
  return (
    <>
      <SearchBox onSubmit={handleSubmit}/>
      {loaded && (
        <div>
          {responses.map((response) => (
            <Card key={response.id} data={response}/>
          ))}
          <Card2 data={city}/>
        </div>
      )}
      {!loaded && <div>Loading...</div>}
    </>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MyComponent/>
      </main>
    </>
  )
}



